uploads = []

[[generated]]
id = "5eDRb1euyhM5gk65e7xN_"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "chicken game icon"

[[outputs]]
id = "GYD9nq4vUXQ7YsAa5kpDb"
uri = "file://artifacts/mobile/assets/sounds/coin.mp3"
type = "audio"
title = "coin_pickup"

[[outputs]]
id = "bl_hWqijfQubTgiYFsRZA"
uri = "file://artifacts/mobile/assets/sounds/music.mp3"
type = "audio"
title = "game_music_loop"

[[outputs]]
id = "vrnKIsdnGBWr9ZPBDm50F"
uri = "file://artifacts/mobile/assets/sounds/traffic.mp3"
type = "audio"
title = "traffic_ambience"

[[outputs]]
id = "1RwKEKlizI4qvXvEeiAZd"
uri = "file://artifacts/mobile/assets/sounds/crash.mp3"
type = "audio"
title = "crash_death"
